version: '2'

volumes:
  orderer.jphr-network.com:
  peer0.patients.jphr-network.com:
  peer1.patients.jphr-network.com:
  peer0.microhealthcareproviders.jphr-network.com:
  peer1.microhealthcareproviders.jphr-network.com:
  peer0.nairobihospital.jphr-network.com:
  peer1.nairobihospital.jphr-network.com:

networks:
  byfn:

services:

  orderer.jphr-network.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.jphr-network.com
    container_name: orderer.jphr-network.com
    networks:
      - byfn

  peer0.patients.jphr-network.com:
    container_name: peer0.patients.jphr-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.patients.jphr-network.com
    networks:
      - byfn

  peer1.patients.jphr-network.com:
    container_name: peer1.patients.jphr-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.patients.jphr-network.com
    networks:
      - byfn

  peer0.microhealthcareproviders.jphr-network.com:
    container_name: peer0.microhealthcareproviders.jphr-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.microhealthcareproviders.jphr-network.com
    networks:
      - byfn

  peer1.microhealthcareproviders.jphr-network.com:
    container_name: peer1.microhealthcareproviders.jphr-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.microhealthcareproviders.jphr-network.com
    networks:
      - byfn

  peer0.nairobihospital.jphr-network.com:
    container_name: peer0.nairobihospital.jphr-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.nairobihospital.jphr-network.com
    networks:
      - byfn

  peer1.nairobihospital.jphr-network.com:
    container_name: peer1.nairobihospital.jphr-network.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.nairobihospital.jphr-network.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.patients.jphr-network.com:7051
      - CORE_PEER_LOCALMSPID=PatientsMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/patients.jphr-network.com/peers/peer0.patients.jphr-network.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/patients.jphr-network.com/peers/peer0.patients.jphr-network.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/patients.jphr-network.com/peers/peer0.patients.jphr-network.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/patients.jphr-network.com/users/Admin@patients.jphr-network.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.jphr-network.com
      - peer0.patients.jphr-network.com
      - peer1.patients.jphr-network.com
      - peer0.microhealthcareproviders.jphr-network.com
      - peer1.microhealthcareproviders.jphr-network.com
      - peer0.nairobihospital.jphr-network.com
      - peer1.nairobihospital.jphr-network.com
    networks:
      - byfn

