version: '2'

services:

  orderer.jphr-network.com:
    container_name: orderer.jphr-network.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/jphr-network.com/orderers/orderer.jphr-network.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/jphr-network.com/orderers/orderer.jphr-network.com/tls/:/var/hyperledger/orderer/tls
    - orderer.jphr-network.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.patients.jphr-network.com:
    container_name: peer0.patients.jphr-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.patients.jphr-network.com
      - CORE_PEER_ADDRESS=peer0.patients.jphr-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.patients.jphr-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.patients.jphr-network.com:7051
      - CORE_PEER_LOCALMSPID=PatientsMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/patients.jphr-network.com/peers/peer0.patients.jphr-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/patients.jphr-network.com/peers/peer0.patients.jphr-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.patients.jphr-network.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.patients.jphr-network.com:
    container_name: peer1.patients.jphr-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.patients.jphr-network.com
      - CORE_PEER_ADDRESS=peer1.patients.jphr-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.patients.jphr-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.patients.jphr-network.com:7051
      - CORE_PEER_LOCALMSPID=PatientsMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/patients.jphr-network.com/peers/peer1.patients.jphr-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/patients.jphr-network.com/peers/peer1.patients.jphr-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.patients.jphr-network.com:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.microhealthcareproviders.jphr-network.com:
    container_name: peer0.microhealthcareproviders.jphr-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.microhealthcareproviders.jphr-network.com
      - CORE_PEER_ADDRESS=peer0.microhealthcareproviders.jphr-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.microhealthcareproviders.jphr-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.microhealthcareproviders.jphr-network.com:7051
      - CORE_PEER_LOCALMSPID=MicroHealthcareProvidersMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/microhealthcareproviders.jphr-network.com/peers/peer0.microhealthcareproviders.jphr-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/microhealthcareproviders.jphr-network.com/peers/peer0.microhealthcareproviders.jphr-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.microhealthcareproviders.jphr-network.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.microhealthcareproviders.jphr-network.com:
    container_name: peer1.microhealthcareproviders.jphr-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.microhealthcareproviders.jphr-network.com
      - CORE_PEER_ADDRESS=peer1.microhealthcareproviders.jphr-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.microhealthcareproviders.jphr-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.microhealthcareproviders.jphr-network.com:7051
      - CORE_PEER_LOCALMSPID=MicroHealthcareProvidersMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/microhealthcareproviders.jphr-network.com/peers/peer1.microhealthcareproviders.jphr-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/microhealthcareproviders.jphr-network.com/peers/peer1.microhealthcareproviders.jphr-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.microhealthcareproviders.jphr-network.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053

  peer0.nairobihospital.jphr-network.com:
    container_name: peer0.nairobihospital.jphr-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.nairobihospital.jphr-network.com
      - CORE_PEER_ADDRESS=peer0.nairobihospital.jphr-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.nairobihospital.jphr-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.nairobihospital.jphr-network.com:7051
      - CORE_PEER_LOCALMSPID=NairobiHospitalMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/nairobihospital.jphr-network.com/peers/peer0.nairobihospital.jphr-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/nairobihospital.jphr-network.com/peers/peer0.nairobihospital.jphr-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.nairobihospital.jphr-network.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053

  peer1.nairobihospital.jphr-network.com:
    container_name: peer1.nairobihospital.jphr-network.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.nairobihospital.jphr-network.com
      - CORE_PEER_ADDRESS=peer1.nairobihospital.jphr-network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.nairobihospital.jphr-network.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.nairobihospital.jphr-network.com:7051
      - CORE_PEER_LOCALMSPID=NairobiHospitalMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/nairobihospital.jphr-network.com/peers/peer1.nairobihospital.jphr-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/nairobihospital.jphr-network.com/peers/peer1.nairobihospital.jphr-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.nairobihospital.jphr-network.com:/var/hyperledger/production
    ports:
      - 12051:7051
      - 12053:7053
